#!/bin/bash
set -e

# 读取安装路径
if [ -f /etc/bbp-chinese/config ]; then
  source /etc/bbp-chinese/config
  [ -n "$INSTALL_PATH" ]
  # 删除文件
  rm -rf "$INSTALL_PATH/BepInEx"
  rm -rf "$INSTALL_PATH/BALDI_Data/StreamingAssets/Modded"
  rm -f "$INSTALL_PATH/readme.txt"
else
  echo "错误：找不到安装记录！" > /dev/tty
fi
