name: Beta version builds

on:
  push:
    branches:
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install NSIS and makepasswd
      run: |
        bash -c 'echo "deb http://ftp.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/unstable.list'
        apt-get -y update
        apt-get -y install -t unstable nsis
        apt-get -y install makepasswd
    - name: Install plugins and set password
      id: passwd
      run: |
        cp PassDialog.dll /usr/share/nsis/Plugins/x86-unicode
        export password=$(makepasswd --chars=16)
        echo "passwd=$password" >> "$GITHUB_OUTPUT"
        sed -i 's/{APASSWORDHERE}/'"$password"'/g' installer.nsi
        sed -i 's/{PASSWORD}/'"$password"'/g' updates.txt
    - name: Build installer
      run: makensis installer.nsi
    - name: Set version and logs and rename the installer
      run: |
        export ver=$(cat ver.txt)
        export gamever=$(cat bbpver.txt)
        export log=$(cat updates.txt)
        mv installer.exe "BB+ $gamever v$ver.exe"
    - name: Check files
      run: ls
    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: BB+ ${{ steps.passwd.outputs.passwd }}
        path: BB+*.exe