name: Beta version builds

on:
  push:
    branches:
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install NSIS
      run: |
        bash -c 'echo "deb http://ftp.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/unstable.list'
        apt-get -y update
        apt-get -y install -t unstable nsis
    - name: Make NSIS installer
      run: makensis installer.nsi
    - name: Check builds
      run: ls