name: Release version builds

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 构建
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - name: 跳过构建
      run: exit 1
    - name: 获取最新版
      uses: actions/checkout@v4
    - name: 安装 NSIS
      run: |
        bash -c 'echo "deb http://ftp.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/unstable.list'
        apt-get -y update
        apt-get -y install -t unstable nsis
    - name: 构建安装程序
      run: makensis installer_release.nsi
    - name: 设置版本、日志并重命名安装程序
      id: sets
      run: |
        ver=$(cat ver.txt)
        gamever=$(cat bbpver.txt)
        sed -i 's/{PASSWORD}/无/g' updates.txt
        log=$(cat updates.txt)
        tag=$(cat ver.txt | tr [:upper:] [:lower:] | tr ' ' '_')
        echo "ver=$ver" >> "$GITHUB_OUTPUT"
        sed -i 's/ver_replace_001/'"$ver"'/g' installer_release.nsi
        echo "gamever=$gamever" >> "$GITHUB_OUTPUT"
        echo "log=$log" >> "$GITHUB_OUTPUT"
        echo "tag=$tag" >> "$GITHUB_OUTPUT"
        mv installer.exe "BB+ $gamever v$ver.exe"
        echo "file_name=BB+ $gamever v$ver.exe" >> "$GITHUB_OUTPUT"
    - name: 创建发行版
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.sets.outputs.tag }}
        release_name: ${{ steps.sets.outputs.ver }}
        body: ${{ steps.sets.outputs.log }}
        draft: false
        prerelease: false
    - name: 上传文件
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ steps.sets.outputs.file_name }}
        asset_name: ${{ steps.sets.outputs.file_name }}
        asset_content_type: application/zip
    - name: 发送通知
      uses: Y2Nk4/qmsg-action@master
      with:
        qq: ${{ secrets.QMSG_NOTIFY_QQ }}
        key: ${{ secrets.QMSG_KEY }}
        message: '${{ github.actor }} 针对 ${{ github.repository }} ${{ github.ref }} 的提交 ${{ github.sha }} (${{ github.event.head_commit.message }}) 的 ${{ github.workflow }} 任务部署完成'
  