name: Beta version builds

on:
  push:
    branches:
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install NSIS and makepasswd
      run: |
        bash -c 'echo "deb http://ftp.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/unstable.list'
        apt-get -y update
        apt-get -y install -t unstable nsis
        apt-get -y install makepasswd
    - name: Install plugins and set password
      run: |
        cp PassDialog.dll /usr/share/nsis/Plugins/x86-unicode
        password=$(makepasswd -l -s 16)
        sed -i 's/{APASSWORDHERE}/$(password)/g' installer.nsi
    - name: Build installer
      run: makensis installer.nsi
    - name: Set version and logs
      run: |
        ver=$(cat ver.txt)
        gamever=$(cat bbpver.txt)
        log=$(cat updates.txt)
    - name: Rename installer
      run: mv installer.exe "BB+ ${gamever} v${ver}.exe"
    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: BB+
        path: installer.exe