name: Beta version builds

on:
  push:
    branches:
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install NSIS
      run: |
        bash -c 'echo "deb http://ftp.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list.d/unstable.list'
        apt-get -y update
        apt-get -y install -t unstable nsis
    - name: Install plugins
      run: cp PassDialog.dll /usr/share/nsis/Plugins/x86-unicode
    - name: Build installer
      run: makensis installer.nsi
    - name: Set version and logs
      run: |
        ver = $(cat ver.txt)
        gamever = $(cat bbpver.txt)
        log = $(cat updates.txt)
    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        name: BB+ ${gamever} v${ver}
        path: installer.exe